### ISSUE TITLE
Cannot select search result when 'All Catagory' is selected.

### ISSUE THREAD

**Issue by galford13x** [Sheep-y/trpg-dnd-4e-db#11]
Problem: Cannot select an item in the list unless a catagory button is selected.
Desire: Generally the search result provides the desired item within the first few rows of the result list (Good job on the search routine).
Fix: The problem is in the - funciton act_list_row_click() - the 'cat' object is not set correctly when 'All Catagory' was last searched.
Change line 3773:
```
if ( ! cat ) cat = this.getAttribute( 'data-category' );	//original
```
to
```
if ( ! cat ) cat = od.data.get( this.getAttribute( 'data-category' ));		// FIXED
```

**Comment by Sheep-y** [comment]
Accidentally closed because of wrong commit message. Reopening.
