### ISSUE TITLE
Internet Explorer 11 Download/Update issue

### ISSUE THREAD

**Issue by galford13x** [Sheep-y/trpg-dnd-4e-db#12]
I've build the latest revision of the project and opened it in Internet Explorer 11.

The Refresh Categories and Check works fine, however, Get All Items and Get new + changed cause a popup that explains a login window will appear etc..  However, no window appears.

I do have popup blocker turned off so that doesn't appear to be the issue.  Should this work fine with IE 11?

**Comment by Sheep-y** [comment]
A new downloader has been [released](https://github.com/Sheep-y/trpg-dnd-4e-db/releases) that works with current DDI compendium.

It is much more production ready than the old version can hope to be, and can deduce new data columns like power frequency or feat requirements.

Now we just need to hope Wizards don't change the login system again. In fact we can't even login with the form displayed on the compendium now, have to go to another page to login first.
