### ISSUE TITLE
Wont download, just opens one window with one compedium entry

### ISSUE THREAD

**Issue by Viscaro** [Sheep-y/trpg-dnd-4e-db#9]
I've been trying to use the 4e_database.html
On the update page, after checking and hitting the get all button, I sign in. A new pop up window appears that displays one compendium entry. For the Class, it opens Cleric (Templar). For Disease, it opens Wererat Filth Fever.

**Comment by Sheep-y** [comment]
Version 3.5 has been released with a new downloader that requires minimal user interaction and does not depends on any browser or browser settings.  Assumed case closed.
